<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
// Isolated in-memory database. Never opens the application's data directory.
require __DIR__.'/../app/Database.php';
require __DIR__.'/../app/AmbassadorProgram.php';
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->exec('PRAGMA foreign_keys=ON');
(new ReflectionMethod(Database::class,'migrate'))->invoke(null,$db);
AmbassadorProgram::migrate($db);
AmbassadorProgram::migrate($db);
$count=0;
$assert=static function(bool $ok,string $name) use (&$count): void { if(!$ok)throw new RuntimeException('FAIL: '.$name);$count++;echo "PASS $name\n"; };
$reject=static function(callable $fn,string $name) use ($assert): void {try{$fn();}catch(InvalidArgumentException $e){$assert(true,$name);return;}$assert(false,$name);};
$admin=(int)$db->query("SELECT id FROM users WHERE role='admin' LIMIT 1")->fetchColumn();
$student=(int)$db->query("SELECT id FROM users WHERE role='student' LIMIT 1")->fetchColumn();
$other=(int)$db->query("SELECT id FROM users WHERE role='ambassador' LIMIT 1")->fetchColumn();
$run=static fn(int $actor,string $action,array $data=[])=>AmbassadorProgram::handle($db,$actor,$action,$data);
$application=['motivation'=>'Muốn hỗ trợ học sinh','topics'=>'Đời sống sinh viên','skills'=>'Lắng nghe','availability'=>'Tối thứ ba','consent'=>'1'];
$reject(fn()=>$run($student,'apply',array_diff_key($application,['consent'=>true])),'consent required');
$run($student,'apply',$application);
$assert((int)$db->query('SELECT COUNT(*) FROM ambassador_applications')->fetchColumn()===1,'application persisted');
$reject(fn()=>$run($student,'review_application',['id'=>$student,'status'=>'approved','note'=>'self approval']),'student cannot approve');
$run($admin,'review_application',['id'=>$student,'status'=>'approved','note'=>'Đã trao đổi định hướng']);
$task=['id'=>$student,'title'=>'Chia sẻ trải nghiệm','kind'=>'content','brief'=>'Nêu rõ góc nhìn cá nhân','due_date'=>date('Y-m-d',strtotime('+7 days'))];
$reject(fn()=>$run($admin,'assign_task',$task),'training prerequisite');
$reject(fn()=>$run($student,'complete_training',['module'=>'privacy','answer'=>'1']),'wrong answer rejected');
foreach(array_keys(AmbassadorProgram::MODULES) as $module)$run($student,'complete_training',['module'=>$module,'answer'=>'0']);
$run($student,'complete_training',['module'=>'privacy','answer'=>'0']);
$assert((int)$db->query('SELECT COUNT(*) FROM ambassador_training')->fetchColumn()===3,'training idempotent');
$reject(fn()=>$run($admin,'assign_task',array_replace($task,['due_date'=>'2026-02-30'])),'invalid date rejected');
$run($admin,'assign_task',$task);
$id=(int)$db->query('SELECT id FROM ambassador_tasks')->fetchColumn();
$reject(fn()=>$run($other,'submit_task',['id'=>$id,'result'=>'Not mine']),'task ownership enforced');
$run($student,'submit_task',['id'=>$id,'result'=>'Đã hoàn thành bản nháp']);
$run($admin,'review_task',['id'=>$id,'status'=>'revision','note'=>'Bổ sung giới hạn trải nghiệm']);
$run($student,'submit_task',['id'=>$id,'result'=>'Đã bổ sung']);
$run($admin,'review_task',['id'=>$id,'status'=>'completed','note'=>'Ghi nhận đóng góp']);
$reject(fn()=>$run($student,'submit_task',['id'=>$id,'result'=>'Overwrite']),'completed task immutable to member');
$run($student,'member_feedback',['decision'=>'paused','note'=>'Xin nghỉ trong kỳ thi']);
$assert($db->query('SELECT participation FROM ambassador_applications')->fetchColumn()==='active','member feedback does not silently change participation');
$run($admin,'review_member',['id'=>$student,'decision'=>'paused','note'=>'Thống nhất tạm nghỉ']);
$reject(fn()=>$run($admin,'assign_task',$task),'paused member cannot receive new work');
$assert(AmbassadorProgram::knowledge($db,true)===[],'legacy sources not falsely verified');
$sourceId=(int)$db->query('SELECT id FROM ai_knowledge_entries LIMIT 1')->fetchColumn();
$source=['id'=>$sourceId,'kind'=>'official','source_url'=>'https://cmcu.edu.vn/','scope'=>'Nguồn kiểm thử','valid_until'=>date('Y-m-d',strtotime('+30 days')),'state'=>'approved'];
$reject(fn()=>$run($student,'save_source',$source),'student cannot verify source');
$reject(fn()=>$run($admin,'save_source',array_replace($source,['source_url'=>'javascript:alert(1)'])),'unsafe URL rejected');
$run($admin,'save_source',$source);
$assert(count(AmbassadorProgram::knowledge($db,true))===1,'verified source eligible');
$db->prepare("UPDATE ai_knowledge_entries SET content=content||' edited' WHERE id=?")->execute([$sourceId]);
$assert(AmbassadorProgram::knowledge($db,true)===[],'content edit invalidates verification');
$run($admin,'save_source',$source);
$db->exec("UPDATE knowledge_governance SET valid_until='2000-01-01'");
$assert(AmbassadorProgram::knowledge($db,true)===[],'expired source excluded');
$run($admin,'save_source',array_replace($source,['kind'=>'experience']));
$assert(AmbassadorProgram::knowledge($db,true)===[],'personal experience never treated as official policy');
$run($admin,'save_source',$source);
$db->prepare('UPDATE ai_knowledge_entries SET is_active=0 WHERE id=?')->execute([$sourceId]);
$assert(AmbassadorProgram::knowledge($db,true)===[],'disabled source excluded');
$audit=json_decode((string)$db->query("SELECT snapshot FROM program_audit WHERE entity='knowledge' ORDER BY id DESC LIMIT 1")->fetchColumn(),true);
$assert(isset($audit['entry']['content'])&&!isset($audit['csrf_token']),'audit stores revision without credentials');
$metrics=AmbassadorProgram::metrics($db);
$assert($metrics['trained']===1&&$metrics['completed_tasks']===1,'metrics derived from stored events');
$run($student,'report_issue',['category'=>'information','detail'=>'Cần làm rõ phạm vi học bổng']);
$reportId=(int)$db->query('SELECT id FROM program_reports LIMIT 1')->fetchColumn();
$reject(fn()=>$run($student,'resolve_report',['id'=>$reportId,'status'=>'resolved','note'=>'Self resolve']),'member cannot close reports');
$run($admin,'resolve_report',['id'=>$reportId,'status'=>'resolved','note'=>'Đã bổ sung phạm vi và yêu cầu xác nhận lại nguồn']);
$assert(AmbassadorProgram::metrics($db)['open_reports']===0,'report resolution reflected in metrics');
$db->exec('DELETE FROM messages; DELETE FROM conversations');
$metrics=AmbassadorProgram::metrics($db);
$assert($metrics['rating']===null&&$metrics['first_reply_minutes']===null,'empty metrics remain unknown');
$assert(!$db->inTransaction(),'all transactions closed');
echo "$count checks passed.\n";
