<?php
require_auth(['admin']);
$pageTitle = 'Đội ngũ đại sứ';
$students = rows("SELECT u.*, (SELECT COUNT(*) FROM conversations c WHERE c.ambassador_id=u.id) AS chats, COALESCE((SELECT SUM(s.views) FROM submissions s WHERE s.user_id=u.id AND s.status='approved'),0) AS views FROM users u WHERE u.role IN ('student','ambassador') ORDER BY u.role = 'ambassador' DESC, u.name");
?>
<div class="page-actions"><p class="page-intro">Quản lý hồ sơ, quyền trực inbox và trạng thái hoạt động.</p><div class="summary-pills"><span><i class="online"></i> <?= (int) scalar("SELECT COUNT(*) FROM users WHERE role='ambassador' AND is_online=1") ?> đang online</span><span><?= (int) scalar("SELECT COUNT(*) FROM users WHERE role='ambassador'") ?> đại sứ</span></div></div>
<section class="panel-card"><div class="panel-head"><div></div><a href="index.php?page=admin-rewards">Quản lý phân hạng <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table clean-table align-middle"><thead><tr><th>Thành viên</th><th>Ngành học</th><th>Vai trò</th><th>Phân hạng</th><th>Hiệu quả</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><?php foreach ($students as $student): ?><tr><td><div class="person-cell"><span class="avatar avatar-sm"><?= AmbassadorProfiles::avatarHtml($student) ?></span><div><strong><?= e($student['name']) ?> <?php if ($student['role'] === 'ambassador'): ?><i class="bi bi-patch-check-fill text-primary"></i><?php endif; ?></strong><small><?= e($student['student_code']) ?> | <?= e($student['hometown']) ?></small><?php if ($student['role'] === 'ambassador'): ?><a class="profile-record-link small" href="index.php?page=admin-ambassadors&amp;profile=<?= (int)$student['id'] ?>#profileEditor">Sửa hồ sơ</a><?php endif; ?></div></div></td><td><?= e($student['major']) ?><small class="d-block text-muted">Năm <?= (int) $student['study_year'] ?></small></td><td><span class="badge text-bg-<?= $student['role'] === 'ambassador' ? 'primary' : 'secondary' ?>-subtle"><?= e(role_label($student['role'])) ?></span></td><td><span class="tier-badge tier-<?= e($student['ambassador_tier']) ?>"><?= e(ucfirst($student['ambassador_tier'])) ?></span></td><td><span class="me-3"><strong><?= (int) $student['chats'] ?></strong> chats</span><span><strong><?= number_format((int) $student['views']) ?></strong> views</span></td><td><span class="presence <?= $student['is_online'] ? 'online' : '' ?>"></span> <?= $student['status'] === 'active' ? 'Hoạt động' : 'Tạm khóa' ?></td><td><form method="post" action="actions.php?action=update_ambassador" class="d-flex gap-2"><?= csrf_field() ?><input type="hidden" name="user_id" value="<?= (int) $student['id'] ?>"><input type="hidden" name="status" value="<?= $student['status'] ?>"><select class="form-select form-select-sm" name="role" aria-label="Vai trò"><option value="student" <?= $student['role'] === 'student' ? 'selected' : '' ?>>Sinh viên</option><option value="ambassador" <?= $student['role'] === 'ambassador' ? 'selected' : '' ?>>Đại sứ</option></select><button class="btn btn-sm btn-light border">Lưu</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php
$profileId=(int)($_GET['profile']??0);
$person=rows("SELECT * FROM users WHERE id=? AND role='ambassador'",[$profileId])[0]??null;
if($person): $details=AmbassadorProfiles::details($db,$profileId);
?>
<section class="panel-card mt-4" id="profileEditor">
<div class="panel-head"><div><h3>Hồ sơ <?= e($person['name']) ?></h3><p>Thông tin này được dùng trên widget và khi AI gợi ý đại sứ.</p></div><a class="btn btn-light" href="index.php?page=widget#profile-<?= $profileId ?>" target="_blank" rel="noopener">Xem hồ sơ</a></div>
<form method="post" action="actions.php?action=save_ambassador_profile">
<?= csrf_field() ?><input type="hidden" name="user_id" value="<?= $profileId ?>">
<div class="row g-3"><?php foreach(['about'=>'Giới thiệu','topics'=>'Chủ đề có thể chia sẻ (ngăn cách bằng |)','activities'=>'Hoạt động','projects'=>'Dự án','languages'=>'Ngôn ngữ','advice'=>'Lời nhắn cho học sinh'] as $key=>$label): ?>
<div class="col-md-6"><label class="form-label" for="profile-<?= $key ?>"><?= e($label) ?></label><textarea class="form-control" id="profile-<?= $key ?>" name="<?= $key ?>" rows="4" maxlength="3000"><?= e($details[$key]??'') ?></textarea></div>
<?php endforeach; ?></div><button class="btn btn-brand mt-3">Lưu hồ sơ</button></form></section>
<?php endif; ?>
