<?php
require_auth(['admin']);
$pageTitle = 'Quản lý chiến dịch';
$campaigns = rows('SELECT c.*, COUNT(DISTINCT s.id) AS submissions, COALESCE(SUM(al.clicks),0) AS clicks, COALESCE(SUM(al.leads),0) AS leads FROM campaigns c LEFT JOIN submissions s ON s.campaign_id = c.id LEFT JOIN affiliate_links al ON al.campaign_id = c.id GROUP BY c.id ORDER BY c.id DESC');
?>
<div class="page-actions"><div><p class="page-intro">Tạo brief, theo dõi UGC và hiệu quả affiliate trên cùng một nơi.</p></div><button class="btn btn-brand" data-bs-toggle="modal" data-bs-target="#campaignModal"><i class="bi bi-plus-lg"></i> Tạo chiến dịch</button></div>
<div class="row g-4">
<?php foreach ($campaigns as $campaign): ?><div class="col-lg-6 col-xxl-4"><article class="campaign-card"><div class="campaign-top"><span class="campaign-icon"><i class="bi bi-camera-reels-fill"></i></span><span class="badge text-bg-<?= e(status_badge($campaign['status'])) ?>-subtle"><?= e($campaign['status']) ?></span></div><h3><?= e($campaign['title']) ?></h3><p><?= e($campaign['description']) ?></p><div class="campaign-meta"><span><i class="bi bi-calendar3"></i> <?= date('d/m/Y', strtotime($campaign['deadline'])) ?></span><span><i class="bi bi-gift-fill"></i> <?= (int) $campaign['reward_points'] ?> điểm</span></div><div class="campaign-stats"><div><strong><?= (int) $campaign['submissions'] ?></strong><span>Bài nộp</span></div><div><strong><?= (int) $campaign['clicks'] ?></strong><span>Clicks</span></div><div><strong><?= (int) $campaign['leads'] ?></strong><span>Leads</span></div></div><button class="btn btn-light border w-100">Xem chi tiết <i class="bi bi-arrow-right"></i></button></article></div><?php endforeach; ?>
</div>
<div class="modal fade" id="campaignModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post" action="actions.php?action=create_campaign"><?= csrf_field() ?><div class="modal-header"><div><p class="eyebrow">NHIỆM VỤ SÁNG TẠO</p><h2 class="modal-title">Tạo chiến dịch mới</h2></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Tên chiến dịch</label><input class="form-control" name="title" required></div><div class="col-12"><label class="form-label">Mô tả ngắn</label><textarea class="form-control" name="description" rows="2" required></textarea></div><div class="col-12"><label class="form-label">Brief chi tiết</label><textarea class="form-control" name="brief" rows="4" required></textarea></div><div class="col-md-6"><label class="form-label">Nền tảng</label><select class="form-select" name="platform"><option>TikTok / Reels</option><option>YouTube Shorts</option><option>Facebook / Instagram</option></select></div><div class="col-md-3"><label class="form-label">Điểm thưởng</label><input class="form-control" type="number" name="reward_points" min="0" value="50"></div><div class="col-md-3"><label class="form-label">Trạng thái</label><select class="form-select" name="status"><option value="active">Hoạt động</option><option value="draft">Bản nháp</option></select></div><div class="col-md-6"><label class="form-label">Hạn nộp</label><input class="form-control" type="date" name="deadline" min="<?= date('Y-m-d') ?>" required></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Hủy</button><button class="btn btn-brand">Phát hành chiến dịch</button></div></form></div></div></div>
