<?php
require_auth(['admin']);
$pageTitle = 'Tổng quan hệ sinh thái';
$metrics = [
    ['label' => 'Leads affiliate', 'value' => scalar('SELECT COUNT(*) FROM leads'), 'change' => '+18.4%', 'icon' => 'bi-person-plus-fill', 'tone' => 'coral'],
    ['label' => 'Cuộc trò chuyện', 'value' => scalar('SELECT COUNT(*) FROM conversations'), 'change' => '+12.1%', 'icon' => 'bi-chat-square-dots-fill', 'tone' => 'blue'],
    ['label' => 'Bài UGC đã nộp', 'value' => scalar('SELECT COUNT(*) FROM submissions'), 'change' => '+24.8%', 'icon' => 'bi-camera-video-fill', 'tone' => 'violet'],
    ['label' => 'Đại sứ hoạt động', 'value' => scalar("SELECT COUNT(*) FROM users WHERE role = 'ambassador' AND status = 'active'"), 'change' => '+2 tháng này', 'icon' => 'bi-people-fill', 'tone' => 'green'],
];
$recentSubmissions = rows('SELECT s.*, u.name AS student_name, c.title AS campaign_title FROM submissions s JOIN users u ON u.id = s.user_id JOIN campaigns c ON c.id = s.campaign_id ORDER BY s.id DESC LIMIT 5');
$topAmbassadors = rows("SELECT u.name, u.major, u.is_online, COUNT(DISTINCT c.id) AS chats, COALESCE(SUM(al.leads),0) AS leads FROM users u LEFT JOIN conversations c ON c.ambassador_id = u.id LEFT JOIN affiliate_links al ON al.user_id = u.id WHERE u.role = 'ambassador' GROUP BY u.id ORDER BY leads DESC, chats DESC LIMIT 4");
?>
<div class="welcome-banner"><div><p class="eyebrow">TỔNG QUAN HÔM NAY</p><h2>Mọi kết nối đang đi đúng hướng.</h2><p>Hệ thống ghi nhận <strong><?= (int) scalar("SELECT COUNT(*) FROM leads WHERE date(created_at) = date('now')") ?> lead mới</strong> và <strong><?= (int) scalar("SELECT COUNT(*) FROM conversations WHERE date(created_at) = date('now')") ?> cuộc trò chuyện</strong> hôm nay.</p></div><div class="banner-spark"><i class="bi bi-graph-up-arrow"></i></div></div>

<div class="row g-4 metric-grid">
    <?php foreach ($metrics as $metric): ?><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon <?= e($metric['tone']) ?>"><i class="bi <?= e($metric['icon']) ?>"></i></span><div><p><?= e($metric['label']) ?></p><h3><?= number_format((int) $metric['value']) ?></h3><small><i class="bi bi-arrow-up-right"></i> <?= e($metric['change']) ?> <em>so với tháng trước</em></small></div></article></div><?php endforeach; ?>
</div>

<div class="row g-4 mt-1">
    <div class="col-xl-8"><section class="panel-card h-100"><div class="panel-head"><div><p class="eyebrow">HIỆU SUẤT 7 NGÀY</p><h3>Leads & cuộc trò chuyện</h3></div><span class="panel-chip"><i></i> Dữ liệu trực tiếp</span></div><div class="chart-legend"><span><i class="lead-color"></i> Leads</span><span><i class="chat-color"></i> Cuộc trò chuyện</span></div><div class="bar-chart" aria-label="Biểu đồ hiệu suất 7 ngày"><?php $bars = [[42,58],[55,44],[48,68],[74,62],[66,78],[88,72],[79,91]]; $days=['T2','T3','T4','T5','T6','T7','CN']; foreach ($bars as $i => $bar): ?><div class="bar-group"><div class="bars"><span style="height:<?= $bar[0] ?>%"></span><span style="height:<?= $bar[1] ?>%"></span></div><small><?= $days[$i] ?></small></div><?php endforeach; ?></div></section></div>
    <div class="col-xl-4"><section class="panel-card h-100"><div class="panel-head"><div><p class="eyebrow">PHỄU CHUYỂN ĐỔI</p><h3>Tháng này</h3></div><button class="icon-btn"><i class="bi bi-three-dots"></i></button></div><div class="funnel-list"><div><span><i class="bi bi-eye-fill"></i> Lượt click</span><strong><?= number_format((int) scalar('SELECT COALESCE(SUM(clicks),0) FROM affiliate_links')) ?></strong><em style="--width:100%"></em></div><div><span><i class="bi bi-person-lines-fill"></i> Leads</span><strong><?= number_format((int) scalar('SELECT COUNT(*) FROM leads')) ?></strong><em style="--width:72%"></em></div><div><span><i class="bi bi-patch-check-fill"></i> Lead đạt chuẩn</span><strong><?= number_format((int) scalar("SELECT COUNT(*) FROM leads WHERE status = 'qualified'")) ?></strong><em style="--width:42%"></em></div></div><div class="conversion-box"><span>Tỷ lệ click → lead</span><strong>6.8%</strong><small><i class="bi bi-arrow-up"></i> 1.2% tháng này</small></div></section></div>
</div>

<div class="row g-4 mt-1">
    <div class="col-xl-7"><section class="panel-card"><div class="panel-head"><div><p class="eyebrow">NỘI DUNG MỚI</p><h3>Bài UGC chờ duyệt</h3></div><a href="index.php?page=admin-submissions">Xem tất cả <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table clean-table"><thead><tr><th>Sinh viên</th><th>Chiến dịch</th><th>Trạng thái</th><th>Ngày nộp</th></tr></thead><tbody><?php foreach ($recentSubmissions as $submission): ?><tr><td><div class="person-cell"><span class="avatar avatar-xs"><?= e(initials($submission['student_name'])) ?></span><strong><?= e($submission['student_name']) ?></strong></div></td><td><?= e($submission['campaign_title']) ?></td><td><span class="badge text-bg-<?= e(status_badge($submission['status'])) ?>-subtle"><?= e(ucfirst($submission['status'])) ?></span></td><td><?= date('d/m', strtotime($submission['submitted_at'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
    <div class="col-xl-5"><section class="panel-card"><div class="panel-head"><div><p class="eyebrow">NGƯỜI TRUYỀN CẢM HỨNG</p><h3>Đại sứ nổi bật</h3></div><a href="index.php?page=admin-ambassadors">Quản lý</a></div><div class="ranking-list"><?php foreach ($topAmbassadors as $i => $ambassador): ?><div class="ranking-item"><b><?= $i + 1 ?></b><span class="avatar avatar-sm"><?= e(initials($ambassador['name'])) ?></span><div><strong><?= e($ambassador['name']) ?></strong><small><?= e($ambassador['major']) ?></small></div><p><strong><?= (int) $ambassador['leads'] ?></strong><small>leads</small></p><span class="presence <?= $ambassador['is_online'] ? 'online' : '' ?>"></span></div><?php endforeach; ?></div></section></div>
</div>
