<?php
require_auth(['student', 'ambassador']);
$pageTitle = 'Link Affiliate cá nhân';
$links = rows('SELECT al.*, c.title AS campaign_title, c.reward_points FROM affiliate_links al JOIN campaigns c ON c.id = al.campaign_id WHERE al.user_id = ? ORDER BY al.id DESC', [user()['id']]);
$availableCampaigns = rows("SELECT c.* FROM campaigns c WHERE c.status = 'active' AND NOT EXISTS (SELECT 1 FROM affiliate_links al WHERE al.campaign_id = c.id AND al.user_id = ?) ORDER BY c.deadline", [user()['id']]);
?>
<div class="affiliate-hero"><div><span class="hero-kicker"><i class="bi bi-link-45deg"></i> AFFILIATE TUYỂN SINH</span><h2>Mỗi lượt chia sẻ,<br><span>một cơ hội kết nối.</span></h2><p>Gắn link cá nhân vào bio hoặc tin nhắn. Hệ thống tự động ghi nhận click, lead và điểm thưởng.</p></div><div class="affiliate-total"><span>Tổng leads</span><strong><?= (int) scalar('SELECT COALESCE(SUM(leads),0) FROM affiliate_links WHERE user_id = ?', [user()['id']]) ?></strong><small>Từ <?= count($links) ?> liên kết</small></div></div>
<div class="row g-4 mt-1"><?php foreach ($links as $link): $url = 'http://' . ($_SERVER['HTTP_HOST'] ?? 'localhost:8000') . '/index.php?page=affiliate&ref=' . urlencode($link['code']); ?><div class="col-xl-6"><article class="link-card"><div class="link-card-head"><span class="link-icon"><i class="bi bi-link-45deg"></i></span><div><small>CHIẾN DỊCH</small><h3><?= e($link['campaign_title']) ?></h3></div><span class="badge text-bg-success-subtle">Đang chạy</span></div><div class="copy-field"><input readonly value="<?= e($url) ?>"><button type="button" data-copy="<?= e($url) ?>"><i class="bi bi-copy"></i> Sao chép</button></div><div class="link-stats"><div><span>Clicks</span><strong><?= (int) $link['clicks'] ?></strong></div><div><span>Leads</span><strong><?= (int) $link['leads'] ?></strong></div><div><span>Chuyển đổi</span><strong><?= $link['clicks'] ? number_format($link['leads'] / $link['clicks'] * 100, 1) : '0.0' ?>%</strong></div></div></article></div><?php endforeach; ?></div>
<?php if ($availableCampaigns): ?><section class="panel-card mt-4"><div class="panel-head"><div><p class="eyebrow">TẠO THÊM LIÊN KẾT</p><h3>Chiến dịch khả dụng</h3></div></div><div class="available-links"><?php foreach ($availableCampaigns as $campaign): ?><form method="post" action="actions.php?action=create_affiliate"><?= csrf_field() ?><input type="hidden" name="campaign_id" value="<?= (int) $campaign['id'] ?>"><div><strong><?= e($campaign['title']) ?></strong><small>Hạn <?= date('d/m/Y', strtotime($campaign['deadline'])) ?> · +<?= (int) $campaign['reward_points'] ?> điểm/bài</small></div><button class="btn btn-outline-brand">Tạo link <i class="bi bi-plus-lg"></i></button></form><?php endforeach; ?></div></section><?php endif; ?>
