<?php
require_auth(['student', 'ambassador']);
$current = user();
$pageTitle = 'Chào ' . explode(' ', $current['name'])[count(explode(' ', $current['name'])) - 1] . '!';
$balance = (int) scalar("SELECT COALESCE(SUM(CASE WHEN type='credit' THEN points ELSE -points END),0) FROM wallet_transactions WHERE user_id = ?", [$current['id']]);
$campaigns = rows("SELECT * FROM campaigns WHERE status = 'active' ORDER BY deadline LIMIT 3");
$transactions = rows('SELECT * FROM wallet_transactions WHERE user_id = ? ORDER BY id DESC LIMIT 4', [$current['id']]);
$clicks = (int) scalar('SELECT COALESCE(SUM(clicks),0) FROM affiliate_links WHERE user_id = ?', [$current['id']]);
$leads = (int) scalar('SELECT COALESCE(SUM(leads),0) FROM affiliate_links WHERE user_id = ?', [$current['id']]);
$conversionRate = $clicks > 0 ? round(($leads / $clicks) * 100, 1) : 0;
$leaderboard = rows(<<<'SQL'
    SELECT u.id, u.name, u.ambassador_tier,
        COALESCE((SELECT SUM(al.leads) FROM affiliate_links al WHERE al.user_id = u.id), 0) AS leads,
        COALESCE((SELECT SUM(CASE WHEN wt.type = 'credit' THEN wt.points ELSE -wt.points END) FROM wallet_transactions wt WHERE wt.user_id = u.id), 0) AS points
    FROM users u
    WHERE u.role IN ('student','ambassador') AND u.status = 'active'
    ORDER BY points DESC, leads DESC, u.name
    LIMIT 5
SQL);
?>
<div class="student-hero"><div><span class="hero-kicker"><i class="bi bi-stars"></i> HÀNH TRÌNH ĐẠI SỨ SỐ</span><h2>Chia sẻ điều thật,<br><span>tạo nên ảnh hưởng thật.</span></h2><p>Khám phá nhiệm vụ mới, kể câu chuyện CMC theo cách của bạn và nhận phần thưởng xứng đáng.</p><a class="btn btn-light btn-lg" href="index.php?page=campaigns">Khám phá nhiệm vụ <i class="bi bi-arrow-right"></i></a></div><div class="student-hero-art"><span class="orbit orbit-one"><i class="bi bi-camera-reels-fill"></i></span><span class="orbit orbit-two"><i class="bi bi-heart-fill"></i></span><span class="hero-avatar"><?= e(initials($current['name'])) ?></span></div></div>
<div class="row g-4 metric-grid mt-1"><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon coral"><i class="bi bi-wallet2"></i></span><div><p>Ví điểm</p><h3><?= number_format($balance) ?></h3><small>Sẵn sàng quy đổi</small></div></article></div><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon violet"><i class="bi bi-camera-video-fill"></i></span><div><p>Bài đã nộp</p><h3><?= (int) scalar('SELECT COUNT(*) FROM submissions WHERE user_id = ?', [$current['id']]) ?></h3><small>Nội dung UGC</small></div></article></div><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon blue"><i class="bi bi-cursor-fill"></i></span><div><p>Lượt click</p><h3><?= (int) scalar('SELECT COALESCE(SUM(clicks),0) FROM affiliate_links WHERE user_id = ?', [$current['id']]) ?></h3><small>Từ link cá nhân</small></div></article></div><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon green"><i class="bi bi-person-check-fill"></i></span><div><p>Leads hợp lệ</p><h3><?= (int) scalar('SELECT COALESCE(SUM(leads),0) FROM affiliate_links WHERE user_id = ?', [$current['id']]) ?></h3><small>Đã ghi nhận</small></div></article></div></div>
<section class="section-block"><div class="panel-head"><div><p class="eyebrow">CƠ HỘI DÀNH CHO BẠN</p><h3>Nhiệm vụ đang diễn ra</h3></div><a href="index.php?page=campaigns">Xem tất cả <i class="bi bi-arrow-right"></i></a></div><div class="row g-4"><?php foreach ($campaigns as $i => $campaign): ?><div class="col-lg-4"><article class="mission-card theme-<?= ($i%3)+1 ?>"><div class="mission-visual"><span><i class="bi <?= $i === 1 ? 'bi-laptop' : 'bi-camera-reels-fill' ?>"></i></span><em><?= e($campaign['platform']) ?></em></div><div class="mission-body"><span class="deadline"><i class="bi bi-clock"></i> Còn <?= max(0, (int) ((strtotime($campaign['deadline']) - time()) / 86400)) ?> ngày</span><h3><?= e($campaign['title']) ?></h3><p><?= e($campaign['description']) ?></p><div class="mission-footer"><strong><i class="bi bi-gift-fill"></i> +<?= (int) $campaign['reward_points'] ?> điểm</strong><a href="index.php?page=campaigns&campaign=<?= (int) $campaign['id'] ?>">Xem brief</a></div></div></article></div><?php endforeach; ?></div></section>
<div class="row g-4"><div class="col-xl-7"><section class="panel-card h-100"><div class="panel-head"><div><p class="eyebrow">THÀNH TÍCH GẦN ĐÂY</p><h3>Dòng điểm thưởng</h3></div><a href="index.php?page=wallet">Xem ví</a></div><div class="transaction-list"><?php foreach ($transactions as $transaction): ?><div><span class="transaction-icon"><i class="bi bi-stars"></i></span><p><strong><?= e($transaction['description']) ?></strong><small><?= date('d/m/Y | H:i', strtotime($transaction['created_at'])) ?></small></p><b class="<?= $transaction['type'] === 'credit' ? 'positive' : 'negative' ?>"><?= $transaction['type'] === 'credit' ? '+' : '-' ?><?= (int) $transaction['points'] ?></b></div><?php endforeach; ?><?php if (!$transactions): ?><div class="empty-state compact">Chưa có giao dịch điểm.</div><?php endif; ?></div></section></div><div class="col-xl-5"><section class="panel-card h-100"><div class="panel-head"><div><p class="eyebrow">LINK CỦA BẠN</p><h3>Biến chia sẻ thành leads</h3></div><span class="metric-icon blue"><i class="bi bi-link-45deg"></i></span></div><div class="mini-affiliate"><p>Mỗi link có mã riêng để hệ thống tự động ghi nhận lượt click và đăng ký.</p><div class="mini-number"><span>Tỷ lệ chuyển đổi</span><strong><?= number_format($conversionRate, 1) ?>%</strong><em><?= $leads ?> leads từ <?= $clicks ?> clicks</em></div><a class="btn btn-brand w-100" href="index.php?page=my-affiliate">Quản lý link Affiliate</a></div></section></div></div>

<section class="panel-card section-block leaderboard-panel"><div class="panel-head"><div><p class="eyebrow">BẢNG XẾP HẠNG THÁNG</p><h3>Những người tạo ảnh hưởng tích cực</h3></div><span class="panel-chip"><i class="bi bi-shield-check"></i> Xếp theo điểm đã xác minh</span></div><div class="leaderboard-list"><?php foreach ($leaderboard as $rank => $member): ?><div class="leaderboard-row <?= (int) $member['id'] === (int) $current['id'] ? 'is-me' : '' ?>"><span class="rank-number"><?= $rank + 1 ?></span><span class="avatar avatar-sm"><?= e(initials($member['name'])) ?></span><p><strong><?= e($member['name']) ?><?= (int) $member['id'] === (int) $current['id'] ? ' (Bạn)' : '' ?></strong><small><span class="tier-badge tier-<?= e($member['ambassador_tier']) ?>"><?= e(ucfirst($member['ambassador_tier'])) ?></span> <?= (int) $member['leads'] ?> leads</small></p><b><?= number_format((int) $member['points']) ?> điểm</b></div><?php endforeach; ?></div></section>
