<?php
require_auth(['ambassador']);
$pageTitle = 'Hộp thư P2P';
$conversations = rows('SELECT c.*, p.name AS prospect_name, p.major, (SELECT content FROM messages WHERE conversation_id = c.id ORDER BY id DESC LIMIT 1) AS last_message, (SELECT created_at FROM messages WHERE conversation_id = c.id ORDER BY id DESC LIMIT 1) AS message_time FROM conversations c JOIN users p ON p.id = c.prospect_id WHERE c.ambassador_id = ? ORDER BY c.last_message_at DESC', [user()['id']]);
$selected = (int) ($_GET['conversation'] ?? ($conversations[0]['id'] ?? 0));
?>
<div class="inbox-shell" data-inbox-conversation="<?= $selected ?>">
    <aside class="inbox-list"><div class="inbox-list-head"><div><p class="eyebrow">TIN NHẮN</p><h3><?= count($conversations) ?> cuộc trò chuyện</h3></div><span class="presence online"></span></div><div class="inbox-search"><i class="bi bi-search"></i><input placeholder="Tìm theo tên..."></div><?php foreach ($conversations as $conversation): ?><a class="inbox-row <?= $selected === (int) $conversation['id'] ? 'active' : '' ?>" href="index.php?page=inbox&conversation=<?= (int) $conversation['id'] ?>"><span class="avatar avatar-sm"><?= e(initials($conversation['prospect_name'])) ?></span><div><strong><?= e($conversation['prospect_name']) ?></strong><small><?= e(mb_substr($conversation['last_message'] ?: 'Bắt đầu cuộc trò chuyện', 0, 48)) ?><?= mb_strlen($conversation['last_message'] ?? '') > 48 ? '…' : '' ?></small></div><time><?= $conversation['message_time'] ? date('H:i', strtotime($conversation['message_time'])) : '' ?></time></a><?php endforeach; ?></aside>
    <section class="inbox-room"><?php if ($selected): $info = rows('SELECT c.*, p.name AS prospect_name, p.major FROM conversations c JOIN users p ON p.id=c.prospect_id WHERE c.id=? AND c.ambassador_id=?', [$selected,user()['id']])[0] ?? null; ?><div class="inbox-room-head"><span class="avatar avatar-sm"><?= e(initials($info['prospect_name'])) ?></span><div><strong><?= e($info['prospect_name']) ?></strong><small>Quan tâm: <?= e($info['major'] ?: 'Chưa xác định') ?></small></div><span class="quality-chip"><i class="bi bi-activity"></i> Quality <?= (int) $info['quality_score'] ?>/100</span><span class="safety-badge"><i class="bi bi-shield-check"></i> Được bảo vệ</span></div><div class="message-list inbox-messages" id="messageList"></div><form class="chat-composer inbox-composer" id="messageForm"><input type="hidden" id="conversationId" value="<?= $selected ?>"><textarea id="messageInput" rows="1" placeholder="Trả lời như một người bạn..."></textarea><button type="submit" aria-label="Gửi tin nhắn"><i class="bi bi-send-fill"></i></button></form><?php else: ?><div class="empty-state"><i class="bi bi-chat-heart"></i><h2>Chưa có tin nhắn</h2><p>Khi học sinh chọn trò chuyện cùng bạn, cuộc hội thoại sẽ xuất hiện tại đây.</p></div><?php endif; ?></section>
    <aside class="inbox-profile"><?php if ($selected && isset($info)): ?><span class="avatar avatar-xl"><?= e(initials($info['prospect_name'])) ?></span><h3><?= e($info['prospect_name']) ?></h3><p>Học sinh THPT</p><div class="profile-fact"><span><i class="bi bi-book"></i></span><div><small>Ngành quan tâm</small><strong><?= e($info['major'] ?: 'Đang khám phá') ?></strong></div></div><div class="profile-fact"><span><i class="bi bi-arrow-left-right"></i></span><div><small>Trạng thái hỗ trợ</small><strong><?= e(match ($info['crm_status']) { 'active' => 'Đang hỗ trợ', 'resolved' => 'Đã giải đáp', default => 'Mới' }) ?></strong></div></div><div class="conversation-tips"><strong>Gợi ý trò chuyện</strong><p><i class="bi bi-check-circle-fill"></i> Chia sẻ trải nghiệm cá nhân</p><p><i class="bi bi-check-circle-fill"></i> Không hứa hẹn về tuyển sinh</p><p><i class="bi bi-check-circle-fill"></i> Dẫn nguồn khi nói về quy chế</p></div><?php endif; ?></aside>
</div>
