<?php
require_auth(['student', 'ambassador']);
$pageTitle = 'Hiệu quả nội dung';
$submissions = rows('SELECT s.*, c.title AS campaign_title FROM submissions s JOIN campaigns c ON c.id = s.campaign_id WHERE s.user_id = ? ORDER BY s.id DESC', [user()['id']]);
$summary = rows('SELECT COALESCE(SUM(views), 0) AS views, COALESCE(SUM(likes), 0) AS likes, COALESCE(SUM(comments), 0) AS comments, COALESCE(SUM(shares), 0) AS shares FROM submissions WHERE user_id = ? AND status = ?', [user()['id'], 'approved'])[0];
?>
<div class="page-actions"><div><p class="page-intro">Theo dõi hiệu quả UGC của bạn sau khi nội dung được duyệt và cập nhật chỉ số.</p></div><a class="btn btn-brand" href="index.php?page=my-submissions"><i class="bi bi-camera-reels-fill"></i> Bài nộp của tôi</a></div>
<div class="row g-4 metric-grid mb-4"><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon blue"><i class="bi bi-eye-fill"></i></span><div><p>Lượt xem</p><h3><?= number_format((int) $summary['views']) ?></h3><small>Nội dung đã duyệt</small></div></article></div><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon coral"><i class="bi bi-heart-fill"></i></span><div><p>Lượt thích</p><h3><?= number_format((int) $summary['likes']) ?></h3><small>Từ các nền tảng</small></div></article></div><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon green"><i class="bi bi-chat-square-text-fill"></i></span><div><p>Bình luận</p><h3><?= number_format((int) $summary['comments']) ?></h3><small>Phản hồi của người xem</small></div></article></div><div class="col-sm-6 col-xl-3"><article class="metric-card"><span class="metric-icon violet"><i class="bi bi-send-fill"></i></span><div><p>Chia sẻ</p><h3><?= number_format((int) $summary['shares']) ?></h3><small>Khả năng lan tỏa</small></div></article></div></div>
<section class="panel-card"><div class="panel-head"><div><p class="eyebrow">NỘI DUNG CỦA BẠN</p><h3>Chỉ số theo bài đăng</h3></div></div><div class="table-responsive"><table class="table clean-table align-middle"><thead><tr><th>Chiến dịch</th><th>Nền tảng</th><th>Trạng thái</th><th>Views</th><th>Likes</th><th>Tương tác</th></tr></thead><tbody><?php foreach ($submissions as $submission): ?><tr><td><a class="content-link" href="<?= e($submission['content_url']) ?>" target="_blank" rel="noopener"><i class="bi bi-play-circle-fill"></i><span><?= e($submission['campaign_title']) ?></span></a></td><td><?= e($submission['platform']) ?></td><td><span class="badge text-bg-<?= e(status_badge($submission['status'])) ?>-subtle"><?= e($submission['status']) ?></span></td><td><?= number_format((int) $submission['views']) ?></td><td><?= number_format((int) $submission['likes']) ?></td><td><small><?= number_format((int) $submission['comments']) ?> bình luận · <?= number_format((int) $submission['shares']) ?> chia sẻ</small></td></tr><?php endforeach; ?><?php if (!$submissions): ?><tr><td colspan="6" class="text-center text-muted py-4">Chưa có bài nộp để thống kê.</td></tr><?php endif; ?></tbody></table></div></section>
