<?php
require_auth(['student', 'ambassador']);
$pageTitle = 'Bài nộp của tôi';
$submissions = rows('SELECT s.*, c.title AS campaign_title, c.reward_points FROM submissions s JOIN campaigns c ON c.id = s.campaign_id WHERE s.user_id = ? ORDER BY s.id DESC', [user()['id']]);
$activeCampaigns = rows("SELECT id, title FROM campaigns WHERE status = 'active' ORDER BY deadline, id");
$statusLabels = ['pending' => 'Chờ duyệt', 'approved' => 'Đã duyệt', 'rejected' => 'Cần chỉnh sửa'];
?>
<div class="page-actions">
    <p class="page-intro">Theo dõi trạng thái xử lý và phản hồi cho từng nội dung đã gửi.</p>
    <div class="d-flex flex-wrap gap-2">
        <button class="btn btn-outline-brand" type="button" data-bs-toggle="modal" data-bs-target="#blogPostModal"><i class="bi bi-journal-richtext"></i> Viết bài blog</button>
        <a class="btn btn-brand" href="index.php?page=campaigns"><i class="bi bi-plus-lg"></i> Nộp nội dung mạng xã hội</a>
    </div>
</div>
<div class="row g-4">
    <?php foreach ($submissions as $submission): ?><div class="col-lg-6"><article class="submission-card">
        <div class="submission-thumb"><i class="bi <?= $submission['content_type'] === 'blog' ? 'bi-journal-richtext' : 'bi-play-circle-fill' ?>"></i><span><?= e($submission['status']) ?></span></div>
        <div class="submission-content"><span class="badge text-bg-<?= e(status_badge($submission['status'])) ?>-subtle"><?= $submission['content_type'] === 'blog' ? 'Bài viết · ' : '' ?><?= e($statusLabels[$submission['status']] ?? $submission['status']) ?></span><h3><?= e($submission['content_type'] === 'blog' ? ($submission['blog_title'] ?: $submission['campaign_title']) : $submission['campaign_title']) ?></h3><p><?= e($submission['content_type'] === 'blog' ? $submission['blog_excerpt'] : $submission['caption']) ?></p><div class="submission-meta"><span><i class="bi bi-calendar3"></i> <?= date('d/m/Y', strtotime($submission['submitted_at'])) ?></span><strong><i class="bi bi-gift-fill"></i> <?= (int) $submission['reward_points'] ?> điểm</strong></div><?php if ($submission['feedback']): ?><div class="feedback-box"><i class="bi bi-chat-quote-fill"></i><div><strong>Phản hồi của người duyệt</strong><p><?= e($submission['feedback']) ?></p></div></div><?php endif; ?>
            <?php if ($submission['content_type'] === 'blog'): ?><div class="blog-submission-note"><i class="bi <?= $submission['status'] === 'approved' ? 'bi-broadcast-pin' : 'bi-hourglass-split' ?>"></i><span><?= $submission['status'] === 'approved' ? 'Đã xuất bản trong mục Nội dung của widget.' : 'Sẽ hiển thị trong widget sau khi được duyệt.' ?></span></div><?php else: ?><a class="btn btn-light border w-100" href="<?= e($submission['content_url']) ?>" target="_blank" rel="noopener">Xem nội dung <i class="bi bi-box-arrow-up-right"></i></a><?php endif; ?>
        </div>
    </article></div><?php endforeach; ?>
    <?php if (!$submissions): ?><div class="col-12"><div class="empty-state"><i class="bi bi-camera-reels"></i><h2>Chưa có bài nộp</h2><p>Chọn chiến dịch, xem yêu cầu và gửi nội dung để bắt đầu.</p><a class="btn btn-brand" href="index.php?page=campaigns">Xem chiến dịch</a></div></div><?php endif; ?>
</div>

<div class="modal fade" id="blogPostModal" tabindex="-1" aria-labelledby="blogPostTitle" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post" action="actions.php?action=submit_blog"><?= csrf_field() ?><div class="modal-header"><div><h2 class="modal-title fs-5" id="blogPostTitle">Tạo bài viết tư vấn</h2><p class="text-muted small mb-0 mt-1">Bài viết được hiển thị trong mục Nội dung của widget sau khi được duyệt.</p></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Chiến dịch liên quan</label><select class="form-select" name="campaign_id" required><option value="">Chọn chiến dịch</option><?php foreach ($activeCampaigns as $campaign): ?><option value="<?= (int) $campaign['id'] ?>"><?= e($campaign['title']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Tiêu đề bài viết</label><input class="form-control" name="blog_title" maxlength="140" required placeholder="Một tuần học ngành CNTT tại CMC có gì?"></div><div class="col-12"><label class="form-label">Mô tả ngắn</label><textarea class="form-control" name="blog_excerpt" rows="2" maxlength="280" required placeholder="Tóm tắt nội dung chính của bài viết..."></textarea></div><div class="col-12"><label class="form-label">Nội dung bài viết</label><textarea class="form-control" name="blog_body" rows="10" required placeholder="Chia sẻ trải nghiệm thực tế, ví dụ cụ thể và lời khuyên hữu ích..."></textarea><div class="form-text">Tối thiểu 120 ký tự. Bài viết hiển thị trong widget sau khi được duyệt.</div></div><div class="col-12"><label class="form-label">Liên kết tham khảo <span class="text-muted">(không bắt buộc)</span></label><input class="form-control" type="url" name="content_url" placeholder="https://..."></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Hủy</button><button class="btn btn-brand" type="submit"><i class="bi bi-send"></i> Gửi duyệt</button></div></form></div></div></div>
