<?php
require_auth(['student', 'ambassador']);
$pageTitle = 'Ví điểm thưởng';
$transactions = rows('SELECT * FROM wallet_transactions WHERE user_id = ? ORDER BY id DESC', [user()['id']]);
$balance = (int) scalar("SELECT COALESCE(SUM(CASE WHEN type='credit' THEN points ELSE -points END),0) FROM wallet_transactions WHERE user_id = ?", [user()['id']]);
$earned = (int) scalar("SELECT COALESCE(SUM(points),0) FROM wallet_transactions WHERE user_id = ? AND type='credit'", [user()['id']]);
?>
<div class="wallet-grid"><section class="wallet-card"><div class="wallet-card-top"><span class="brand-mark"><i class="bi bi-stars"></i></span><small>CMC REWARDS</small></div><p>Số dư khả dụng</p><h2><?= number_format($balance) ?> <span>điểm</span></h2><div class="wallet-card-bottom"><span><?= e(user()['name']) ?></span><span>•••• <?= str_pad((string) user()['id'], 4, '0', STR_PAD_LEFT) ?></span></div></section><div class="wallet-summary"><article><span class="metric-icon green"><i class="bi bi-arrow-down-left"></i></span><div><p>Tổng đã nhận</p><strong>+<?= number_format($earned) ?></strong><small>điểm tích lũy</small></div></article><article><span class="metric-icon coral"><i class="bi bi-gift-fill"></i></span><div><p>Có thể quy đổi</p><strong><?= number_format($balance) ?></strong><small>điểm hiện tại</small></div></article></div></div>
<div class="row g-4 mt-1"><div class="col-xl-8"><section class="panel-card"><div class="panel-head"><div><p class="eyebrow">LỊCH SỬ ĐIỂM</p><h3>Giao dịch gần đây</h3></div><select class="form-select form-select-sm w-auto"><option>Tất cả giao dịch</option></select></div><div class="transaction-list detailed"><?php foreach ($transactions as $transaction): ?><div><span class="transaction-icon <?= $transaction['type'] ?>"><i class="bi <?= $transaction['reference_type'] === 'lead' ? 'bi-person-check-fill' : 'bi-camera-video-fill' ?>"></i></span><p><strong><?= e($transaction['description']) ?></strong><small><?= date('d/m/Y H:i', strtotime($transaction['created_at'])) ?> | <?= e($transaction['reference_type'] ?: 'Thưởng') ?></small></p><b class="<?= $transaction['type'] === 'credit' ? 'positive' : 'negative' ?>"><?= $transaction['type'] === 'credit' ? '+' : '-' ?><?= (int) $transaction['points'] ?></b></div><?php endforeach; ?></div></section></div><div class="col-xl-4"><section class="panel-card"><div class="panel-head"><div><p class="eyebrow">QUY ĐỔI</p><h3>Phần thưởng</h3></div></div><div class="reward-list"><div><span><i class="bi bi-mortarboard"></i></span><p><strong>Điểm rèn luyện</strong><small>100 điểm CMC = 5 ĐRL</small></p><button class="btn btn-sm btn-light" <?= $balance < 100 ? 'disabled' : '' ?>>Đổi</button></div><div><span><i class="bi bi-gift"></i></span><p><strong>Quà tặng CMC</strong><small>Từ 250 điểm</small></p><button class="btn btn-sm btn-light" <?= $balance < 250 ? 'disabled' : '' ?>>Đổi</button></div><div><span><i class="bi bi-credit-card"></i></span><p><strong>Hỗ trợ hoạt động</strong><small>Từ 500 điểm</small></p><button class="btn btn-sm btn-light" <?= $balance < 500 ? 'disabled' : '' ?>>Đổi</button></div></div><p class="helper-note"><i class="bi bi-info-circle"></i> Quy đổi sẽ được phòng Công tác Sinh viên xác nhận.</p></section></div></div>
