<?php
require_auth(['student', 'ambassador']);
$pageTitle = 'Điểm thưởng';
$transactions = rows('SELECT * FROM wallet_transactions WHERE user_id = ? ORDER BY id DESC', [user()['id']]);
$balance = (int) scalar("SELECT COALESCE(SUM(CASE WHEN type='credit' THEN points ELSE -points END),0) FROM wallet_transactions WHERE user_id = ?", [user()['id']]);
$earned = (int) scalar("SELECT COALESCE(SUM(points),0) FROM wallet_transactions WHERE user_id = ? AND type='credit'", [user()['id']]);
$spent = (int) scalar("SELECT COALESCE(SUM(points),0) FROM wallet_transactions WHERE user_id = ? AND type='debit'", [user()['id']]);
?>
<div class="wallet-grid"><section class="wallet-card"><div class="wallet-card-top"><span class="brand-mark"><i class="bi bi-stars"></i></span><small>ĐIỂM THƯỞNG CMC</small></div><p>Số điểm hiện có</p><h2><?= number_format($balance) ?> <span>điểm</span></h2><div class="wallet-card-bottom"><span><?= e(user()['name']) ?></span><span><?= e(user()['student_code'] ?? '') ?></span></div></section><div class="wallet-summary"><article><span class="metric-icon green"><i class="bi bi-arrow-down-left"></i></span><div><p>Tổng điểm đã nhận</p><strong><?= number_format($earned) ?></strong><small>điểm</small></div></article><article><span class="metric-icon coral"><i class="bi bi-arrow-up-right"></i></span><div><p>Tổng điểm đã sử dụng</p><strong><?= number_format($spent) ?></strong><small>điểm</small></div></article></div></div>
<div class="row g-4 mt-1"><div class="col-xl-8"><section class="panel-card"><div class="panel-head"><div><h3>Lịch sử điểm</h3></div><select class="form-select form-select-sm w-auto" aria-label="Lọc lịch sử điểm"><option>Tất cả giao dịch</option></select></div><div class="transaction-list detailed"><?php foreach ($transactions as $transaction): ?><div><span class="transaction-icon <?= $transaction['type'] ?>"><i class="bi bi-camera-video-fill"></i></span><p><strong><?= e($transaction['description']) ?></strong><small><?= date('d/m/Y H:i', strtotime($transaction['created_at'])) ?> · <?= e($transaction['reference_type'] ?: 'Thưởng') ?></small></p><b class="<?= $transaction['type'] === 'credit' ? 'positive' : 'negative' ?>"><?= $transaction['type'] === 'credit' ? '+' : '-' ?><?= (int) $transaction['points'] ?></b></div><?php endforeach; ?></div></section></div><div class="col-xl-4"><section class="panel-card"><div class="panel-head"><div><h3>Quyền lợi theo điểm</h3></div></div><div class="reward-list"><div><span><i class="bi bi-mortarboard"></i></span><p><strong>Điểm rèn luyện</strong><small>100 điểm CMC = 5 ĐRL</small></p><span class="reward-threshold"><?= $balance >= 100 ? 'Đủ điều kiện' : 'Cần thêm '.number_format(100-$balance).' điểm' ?></span></div><div><span><i class="bi bi-gift"></i></span><p><strong>Quà tặng CMC</strong><small>Yêu cầu tối thiểu 250 điểm</small></p><span class="reward-threshold"><?= $balance >= 250 ? 'Đủ điều kiện' : 'Cần thêm '.number_format(250-$balance).' điểm' ?></span></div><div><span><i class="bi bi-credit-card"></i></span><p><strong>Hỗ trợ hoạt động</strong><small>Yêu cầu tối thiểu 500 điểm</small></p><span class="reward-threshold"><?= $balance >= 500 ? 'Đủ điều kiện' : 'Cần thêm '.number_format(500-$balance).' điểm' ?></span></div></div><p class="helper-note"><i class="bi bi-info-circle"></i> Liên hệ Phòng Công tác sinh viên để xác nhận điều kiện và thực hiện quy đổi.</p></section></div></div>
